spring:
  application:
    name: person-service
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8088

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 0