spring:
  application:
    name: person-service
  boot:
    admin:
      client:
        instance:
          api-gateway-port: 17957
          management-base-url: http://localhost:${spring.boot.admin.client.instance.api-gateway-port}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

url:
  services:
    location: http://localhost:${spring.boot.admin.client.instance.api-gateway-port}/location-service

server:
  port: 0